# Generated by Django 4.2.2 on 2023-06-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mundo1real", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=100)),
                ("valor", models.IntegerField(max_length=20)),
                ("ativo", models.BooleanField(default=False)),
            ],
        ),
    ]
